package com.captions;

public class DataStoreInString {

    public static String[] pages = new String[]{
            "People say nothing is impossible, but I do nothing every day.",
            "If you think nothing is impossible, try slamming a revolving door.",
            "I finally realized that people are prisoners of their phones… that’s why it’s called a “cell” phone.",
            "There are 100 billion nerves in the human body, and there are people who have the ability to irritate all of them.",
            "Your secrets are safe with me… I wasn’t even listening.",
            "You never realize what you have until it’s gone. Toilet paper is a good example.",
            "I don’t think inside the box and I don’t think outside the box… I don’t even know where the box is.",
            "Be careful when you follow the masses. Sometimes the M is silent.",
            "I would like to thank my arms for always being by my side, my legs for always supporting me, and my fingers because I can always count on them.",
            "Don’t be ashamed of who you are. That’s your parents’ job.",
            "It may look like I’m doing nothing, but in my head, I’m quite busy.",
            "When people tell me “You’re going to regret that in the morning,” I sleep in until noon because I’m a problem solver.",
            "Doing nothing is hard, you never know when you’re done.",
            "If you fall, I will be there. Signed: Floor.",
            "You can’t run through a campground. You can only “ran,” because it’s past tents.",
            "Dear autocorrect, that’s not what I was trying to say. I’m getting tired of your shirt.",
            "Out of my mind! Back in five minutes.",
            "To make time fly, throw your watch out the window.",
            "I don’t like violence but I don’t mind if I get hit by luck.",
            "People say “go big or go home” like going home is a bad thing. Heck yeah, I want to go home, and I’ll have a nap when I get there.",
            "He who laughs last didn’t get it.",
            "It sure is strange that after Tuesday the rest of the week spells WTF.",
            "Yes, I know there is a really special place in Hell for me. It is called a throne.",
            "I eat cake because it’s somebody’s birthday somewhere.",
            "My friend thinks he’s smart. He said onions are the only food that makes you cry. So I threw a coconut at his face.",
            "Vodka may not be the answer but it’s worth a shot.",
            "Wine + dinner = winner",
            "I never make the same mistake twice. I make it like five or six times, you know, just to be sure.",
            "Yesterday I really wanted tacos. Now I’m eating tacos. Follow your dreams.",
            "I need a six-month vacation twice a year.",
            "I’m sorry, I don’t take orders. I barely take suggestions.",
            "You just can’t live a full life on an empty stomach.",
            "Reality called, so I hung up.",
            "I followed a diet but it didn’t follow me back, so I unfollowed it.",
            "The fridge is a clear example that what matters is on the inside.",
            "“Never put off till tomorrow what may be done the day after tomorrow just as well.” ― Mark Twain",
            "“A day without sunshine is like, you know, night.” ― Steve Martin",
            "“Some people never go crazy. What truly horrible lives they must lead.” ― Charles Bukowski",
            "“The reason I talk to myself is because I’m the only one whose answers I accept.” ― George Carlin",
            "“I am free of all prejudice. I hate everyone equally. ” ― W.C. Fields",
            "“Two wrongs don’t make a right, but they make a good excuse.” ― Thomas Szasz",
            "“I generally avoid temptation unless I can’t resist it.” ― Mae West",
            "“If I’m not complaining, I’m not having a good time, hah hah!” ― Martin Scorsese",
            "“No man can be wise on an empty stomach.” – George Eliot",
            "”I am thankful for laughter, except when milk comes out of my nose.” – Woody Allen",
    };

    public static String[] cool = new String[]
            {

                    "Being cool is being your own self, not doing something that someone else is telling you to do.",
                    "I can take it. The tougher it gets, the cooler I get.",
                    "I’m a mirror. If you’re cool with me, I’m cool with you, and the exchange starts. What you see is what you reflect. If you don’t like what you see, then you’ve done something. If I’m standoffish, that’s because you are.",
                    "Nothing is cooler and more attractive than a big comeback, and that’ll be me.",
                    "I’ve never been cool and I don’t really care about being cool. It’s just an awful lot of time and hair gel wasted.",
                    "He who keeps his cool best wins.",
                    "Just keep your cool and your sense of humor.",
                    "Forget the failures. Keep the lessons.",
                    "If you can’t change your fate, change your attitude.",
                    "Those who think it is not cool to be kind are cold-hearted.",
                    "Women are like teabags. We don’t know our true strength until we are in hot water!",
                    "Sometimes one day changes everything; sometimes years change nothing.",
                    "If you are always trying to be normal, you will never know how amazing you can be.",
                    "See the bowtie? I wear it and I don’t care. That’s why it’s cool.",
                    "You don’t have to make something that people call art. Living is an artistic activity, there is an art to getting through the day.",
                    "Secrets…are the very root of cool.",
                    "Passion isn’t cool, it’s hot.",
                    "So, here’s a really stupid thing about the world: The trick to looking cool is not caring whether you look cool. So the moment you achieve perfect coolness is simultaneously the moment that you actually, completely don’t care.",
                    "So uncool it’s cool again.",
                    "People trying too hard to be cool often end up becoming a joke.",
                    "Weird is the new cool"

            };




    public static String[] summer = new String[]
            {
                    "I sea you!",
                    "Shore thing.",
                    "Getting my vitamin sea.",
                    "Sea’s the day.",
                    "Feeling salty.",
                    "Long time no sea.",
                    "This is my resting beach face.",
                    "Mermaid vibes.",
                    "Hit me on my shell phone.",
                    "Living for sandals, sunshine, and sangria.",
                    "If the sun’s out, so am I.",
                    "It’s the time of year to stay up under the stars and then sleep in the sun.",
                    "Not a cloud in the sky or a negative thought in my mind.",
                    "The best kind of kiss is from the sun.",
                    "The only flop in my summer will be flip-flops.",
                    "Girls just wanna have sun.",
                    "Waves hitting the shore is this summer’s soundtrack.",
                    "Eat, swim, sleep, repeat.",
                    "If you’re not in a bikini, you’re overdressed.",
                    "Freedom feels a lot like the summer breeze"
            };

    public static String[] lyrics = new String[]
            {           "I'm the best thing since sliced bread. I'm a damn sandwich.",
                    "Stackin' my money 'til it's in the clouds, I'm a real-life boss man.",
                    "I'm from the Midwest so I'm grindin' for mine.",
                    "I'm the bad guy, duh!",
                    "Laugh now cry later, that's just how I live my life.",
                    "If it rains, then party indoors.",
                    "My momma don't like you and she likes everyone.",
                    "Keep your head up high and your middle finger higher.",
                    "Nothin' lasts forever but the memories we make.",
                    "Pain is beauty, that's just how I roll.",
                    "My name is not important, just know that I'm makin' hits.",
                    "Chill out, it's just a party.",
                    "I'm so fresh they call me Mr. Clean.",
                    "Live for today, 'cause tomorrow ain't guaranteed.",
                    "Saying goodbye is never easy, but I know that we'll meet again someday.",
                    "My life is a movie and you're just a character.",
                    "I'm not tryin' to be perfect, I'm just tryin' to be me.",
                    "I don't need your approval, love me or hate me.",
                    "Roll! Rolls-Royce! That's how I roll.",
                    "I'm not normal, I'm extraordinary.",
                    "If you're not first, you're last.",
                    "I'm a work in progress.",
                    "I don't care what people say, I'mma do me.",
                    "You can't keep me down, I'm rising up.",
                    "My life is my story and I'm writing it my way.",
                    "It's not over until I say it is.",
                    "I'm just a simple girl living life one day at a time.",
                    "Enjoy the journey, not just the destination.",
                    "I'm not afraid to be different.",
                    "Life is too short to waste time on things that don't matter.",
                    "Saddle up, it's time for a wild ride.",
                    "This is my life and I'm living it my way.",
                    "Listen to your heart, not what other people tell you.",
                    "I'm not perfect, but I'm authentic.",
            };

public static String[] BestFriends = new String[]
        {
                "God made us best friends because He knew our moms couldn’t handle us as sisters.",
                "When I say I won’t tell anyone, my best friend doesn’t count.",
                "You are my best friend because I wouldn’t dare be this weird with anyone else.",
                "Strangers think I’m quiet, my friends think I’m outgoing, but my best friends know that I’m completely insane.",
                "Friends knock on the door. Best friends walk into your house and start eating.",
                "We all have that one friend who never learned how to whisper.",
                "Only trust someone who can see these three things: the sorrow behind your smile, the love behind your anger, and the reason behind your silence.",
                "You know who your real friends are when you pull away from them and see who wonders why you are pulling away.",
                "Some people talk to you in their free time and some people free their time to talk to you.",
                "It’s not about who’s real to your face, it’s about who stays real behind your back.",
                "You might not always be next to me, but I know you’ll always have my back.",
                "You’ll know the people who feed your soul because you’ll feel good after spending time with them.",
                "As we grow up, we realize it’s less important to have a ton of friends and more important to have real ones.",
                "Hard times will always reveal true friends.",
                "Real isn’t who’s with you at your celebration; real is who’s standing next to you at rock bottom.",
                "The only people I owe my loyalty to are those who never made me question theirs.",
                "You should never have to think twice about who your real friends are.",
                "Fake friends believe in rumors; real friends believe in you.",
                "If someone seriously wants to be part of your life, they will make an effort to be in it. No reasons. No excuses.",
                "Be with those who bring out the best, not the stress, in you.",
                "A friend is someone who can see the truth and pain in you, even when you’re fooling everyone else.",
                "Friends don’t leave their friends for other people.",
                "No matter how big the crowd, I’ll always be able to find you.",
                "Real friends don’t tell you pretty lies. They tell you the ugly truth.",
                "Side by side or miles apart, real friends are always close to the heart.",
                "Nothing makes the earth seem so spacious as to have friends at a distance; they make the latitudes and longitudes.",
                "The most memorable people in life will be the friends who loved you when you weren’t very lovable.",
                "F.R.I.E.N.D.S: Fight for you. Respect you. Include you. Encourage you. Need you. Deserve you. Stand by you.",
                "A friend is one who overlooks your broken fence and admires the flowers in your garden.",
                "We will always be best friends until we are old and senile. Then we can be new friends.",
                "True friends don’t judge each other. They judge other people together.",
                "Best friends don’t care if your house is clean. They care if you have wine.",
                "When my best friend and I first met, we were both like, “You’re really weird.”",
                "I hope we’re friends until we die. Then, I hope we stay ghost friends so we can walk through walls and scare people.",
                "Just remember, if we get caught, you’re deaf and I don’t speak English.",
                "We’ll be the old ladies causing trouble in the nursing home.",
                "Friends come and go like waves of the ocean, but the true ones stick like an octopus on your face.",
                "Friends never ask for food. Best friends are the reason you have no food.",
                "A good friend knows how you take your coffee. A great friend adds booze.",
                "Friendship is finding that special someone you can enjoy being a dumbass with.",
                "If I send you my ugly selfies, our friendship is real.",
                "Life is too short to be serious all the time. So, if you can’t laugh at yourself, call me—I’ll laugh at you.",
                "Never let your friends feel lonely… disturb them all the time.",
                "Real friendship is when your friend comes over to your house just take a nap.",
                "I love that I don’t have to act socially acceptable around you.",
                "If you aren’t somewhat crazy in the head, I’m afraid we can’t be friends.",
                "If you don’t own matching shirts, are you really friends?",
                "Friends ‘till the end.",
                "A true friend is one soul in two bodies.",
                "Your vibe attracts your tribe.",
                "Friends don’t let friends do silly things alone.",
                "I’ll even send you the photos I look bad in.",
                "Besides chocolate, you’re my favorite.",
                "Love is beautiful, friendship is better",
                "Every girl needs a boy best friend.",
                "No friendship is an accident.",
                "I love my crazy best friends.",
                "Life is better with true friends.",
                "Friends become our chosen family!",
                "Live for the moments you can’t put in words.",
                "Good Times + Crazy Friends = Great Memories!",
                "Life was meant for best friends and good adventures!",
                "I don’t know what I did to deserve a best friend like you.",
                "Meet my Partner in Crime!",
                "Forever and Always.",
                "Rain or Shine.",
                "You are my sunshine on a rainy day.",
                "You drive me crazy, but I love it.",
                "Best friend? Nah. She’s my sister.",
                "Life’s too short and so are we.",
                "You’re the Betty to my Veronica.",
                "Always better together.",
                "Victoria’s Secret models, we comin’ for your careers.",
                "We don’t see any competition.",
                "Real queens fix each other’s crowns.",
                "The sunshines of my life.",
                "Pizza and you are all I need.",
                "On our worst behavior.",
                "Let’s wander.",
                "The bags under our eyes are Gucci",
                "Reality called, school’s back, so we hung up.",
                "And so the adventure begins…",
                "You CAN sit with us.",
                "Friends who slay together, stay together.",
                "A girl can survive without a boyfriend, but she can’t survive without a best friend.",
                "One friend can change your whole life. I know (name) did.",
                "When it hurts to look back and you’re afraid to look ahead, you can look beside you and your best friend will be there.",
                "You are my best friend, my human diary, and my other half. You mean the world to me and I love you.",
                "Best friends believe in you when you don’t believe in yourself.",
                "A good friend knows all your stories. A best friend helped you write them.",
                "Best friends are the people in your life that make you laugh louder, smile brighter, and live better.",
                "Sometimes being with your best friend is all the therapy you need.",
                "A best friend is someone who loves you when you forget to love yourself.",
                "Friends come and go. Best friends will always find their way back.",
                "Best friends are the people you can do anything and nothing with and still have the best time.",
                "A best friend is like a four-leafed clover: hard to find and lucky to have.",
                "Friends listen to what you say. Best friends listen to what you don’t say.",
                "Best friends are those who share your problems so you don’t have to go through them alone.",
                "Friends pick us up when we fall down, and if they can’t pick us up they lie down and listen for awhile.",
                "Real friends get respected, treated, and loved like family.",
                "Frankly, I can’t imagine not being around someone as amazing as you.",
                "Best friend: one million memories, ten thousand inside jokes, one hundred shared secrets.",
                "Nothing could ever replace my best friend.",
                "True friendship is not about being inseparable—it is being separated and finding nothing changes.",
                "Time and good friends are two things that become more valuable the older you get.",
                "Good friends show their love in times of trouble, not just in times of happiness.",
                "Friendship isn’t a big thing, it’s a million little things.",
                "Someday, you’ll need some support in your life, and I promise I’ll be right by your side.",
                "Friends until the very end—and then some."
        };

        public static String[] couples = new String[]
                {
                        "I'm wearing the smile you gave me.",
                        "The best things in life are better with you.",
                        "You're my favorite hello and my hardest goodbye.",
                        "The peanut butter to my jelly.",
                        "Together is a wonderful place to be.",
                        "I can't live without you, and I don't want to try.",
                        "My favorite fairytale is our love story.",
                        "Home is wherever I'm with you.",
                        "Two heads, one heart.",
                        "Every day with you is the best day of my life.",
                        "I want to be with you until my last page.",
                        "P.S. I love you.",
                        "You're the apple of my eye.",
                        "You're my lobster.",
                        "He's the Jim to my Pam.",
                        "We have a forever type of love.",
                        "Only a fool for you.",
                        "We go together like hot sauce and everything.",
                        "Thank you, Tinder.",
                        "Here's to being my emergency contact.",
                        "A relationship is when one person is always right and the other person is the boyfriend.",
                        "I love you more than pizza, and that's saying a lot.",
                        "Swiped right, now it's for life.",
                        "Even when I want to kill you, I love you.",
                        "Thanks for being so good at killing spiders.",
                        "I'm happy to be your big/little spoon.",
                        "He's not perfect, but at least he's not from my hometown.",
                        "I like you even when I'm hungry.",
                        "Thanks for putting up with me even though I'm kind of crazy.",
                        "It wasn't love at first sight, but we turned out okay.",
                        "You're the only person I would share my snacks with.",
                        "I love you ALMOST as much as tacos.",
                        "Here's our submission for the cutest couple award.",
                        "Not McDonald's but he/she's lovin' it.",
                        "Keep calm and give me a kiss.",
                        "I know I’m a handful, but that’s why you’ve got two hands.",
                        "I like my coffee how I like myself: Dark, bitter, and too hot for you.",
                        "Together, we’ll put Hershey’s out of business! That’s how sweet the two of us are.",
                        "I like you more than pizza and I really like pizza.",
                        "I love him a latte.",
                        "I love you with all my butt. I would say heart, but my butt is bigger.",
                        "You make me smile so much that my face cramps up.",
                        "I love you with every pizza my heart!",
                        "Kissing burns 6.4 calories per minute. Wanna make out?",
                        "Let’s cuddle so I can steal your body heat.",
                        "Love is an ocean of emotions entirely surrounded by expenses.",
                        "My favorite place is inside your hug.",
                        "The first time I texted her, she didn’t reply because she fainted.",
                        "We go together like cupcakes and frosting."

                };

        public static  String[] birthday = new String[]
                {
                        "A year wiser 🤓",
                        "Go shawty, it’s my birthday",
                        "Happy birthday to me!",
                        "Having my cake and eating it too 🎂",
                        "Making my birthday wish",
                        "I’m officially [age]!",
                        "Experience level: [age]",
                        "Another year older, wiser, and happier",
                        "On this day, a queen was born. Happy birthday to me!",
                        "Gonna party like my birthday… oh wait, it is!",
                        "Today is my birthday but I'll take gifts whenever.",
                        "A star was born today. Where's *my* movie?",
                        "You're looking at the best party favor.",
                        "Sassy since birth.",
                        "I don't get older, I level up.",
                        "Today, the world received a gift. It's me and you're welcome.",
                        "Don't grow up, it's a trap.",
                        "Age is just a hashtag.",
                        "I can't help being cute, I was born this way.",
                        "May the fork be with you. Let's eat cake.",
                        "I'm not getting older. I'm getting better.",
                        "Facebook has some exciting news today.",
                        "Birthdays are good for me. The more I have, the longer I live.",
                        "When the candles cost more than the cake, it’s time to realize you’re getting old.",
                        "Another year older, another year wiser? I guess we'll see!",
                        "Well, at least I am not as old as I will be next year!",
                        "Of course, I don’t know how to act my age. I’ve never been this age before!",
                        "The only things getting LIT today are the candles on my cake!",
                        "I’m too young to be this old.",
                        "New year, same me... because I'm already awesome.",
                        "Age is merely the number of years the world has been enjoying me.",
                        "I'm just here for the birthday cake.",
                        "I can't keep calm, it's my birthday.",
                        "Here’s my obligatory birthday selfie!",
                        "It’s my favorite holiday…my birthday!",
                        "I have a craving for cake…It must be my birthday week.",
                        " Just went on my annual birthday shopping spree!",
                        "Act my age? No thanks!",
                        "Birthdays are good for you. Statistics show that the more you have the longer you live.",
                        "On this day a star was born.",
                        "Birthdays are the universe's way us of telling us to eat more cake.",
                        "Let me be the first one to wish myself a happy birthday!"
                };


        public  static  String[] sort = new String[]
                {
                        "Oh hey there!",
                        "Short and sweet",
                        "I got nothing",
                        "*Insert witty Instagram caption here*",
                        "Just livin’ life",
                        "Just chillin’",
            "Today’s perfect",
            "Yup, another food pic",
            "Why so serious?",
            "Time for a change",
            "You know what time it is",
            "Live a good story.",
            "Escape the ordinary.",
            "The best is yet to come.",
            "These are days we live for.",
            "Life happens, coffee helps.",
            "Short sassy cute & classy.",
            "The future is bright.",
            "50% savage, 50% sweetheart.",
            "Always be happy",
            "Dance and singing",
            "Don’t, worry be happy",
            "Give respect to elders",
            "Make passion, strength",
            "Rain fall",
            "Read books",
            "Set an alarm",
            "Spread your love",
            "Trust on your lover’s",
            "Wait for food",
            "Your voice favorite"
                };

        public static String[] oneword = new String[]
    {
                "Crazy",
                "Notorious",
                "Karma",
                "Interesting",
                "Cutie",
                "Classy",
                "Sparkle",
                "Sassafrass",
                "Independent",
                "Unbothered",
                "Mood",
                "Lit",
                "Relatable",
                "Eyeroll",
                "Whatever",
                "XOXO",
                "Reckless",
                "Ambitious",
                "Blessed",
                "Yeehaw",
                "Yeet",
                "YOLO",
                "Queen",
                "Shopaholic",
                "Boom",
                "Bad",
                "Boss",
                "Thotty",
                "Sasshole",
                "Unicorn",
                "Sore",
                "Bye",
                "Flawsome",
                "Priorities",
                "Always",
                "BFF",
                "BFF4Ever",
                "Besties",
                "Buddies",
                "Brotherhood",
                "Brothers",
                "Bros",
                "Chillin",
                "Chill",
                "Cheers",
                "Daytrip",
                "Dudes",
                "Dude",
                "Dreamers",
                "Enjoy",
                "Enjoying",
                "Eye-roll",
                "Fashionistas",
                "Fellas",
                "Forever",
                "Friend",
                "Friendship",
                "F.R.I.E.N.D.S.",
                "Fun",
                "Gang",
                "Giggles",
                "Girls",
                "Goofball",
                "Goofballs",
                "Happy",
                "Happiness",
                "Inseparable",
                "Jokers",
                "Laugh",
                "Laughing",
                "LOL",
                "Nostalgic",
                "Remember",
                "Rebels",
                "Roadtrip",
                "ROFL",
                "Sisters",
                "Secrets",
                "Support",
                "Sisterhood",
                "TBT",
                "Together",
                "Us",
                "Weirdos",
                "Angel",
                "Aries",
                "Aquarius",
                "Babe",
                "Bad",
                "Badass",
                "Beauty",
                "Bling",
                "Bold",
                "Bored",
                "Brave",
                "Cancer",
                "Capricorn",
                "Change",
                "Classy",
                "Cool",
                "Coffee",
                "Colorful",
                "Confident",
                "Crazy",
                "Creative",
                "Curls",
                "Cute",
                "Daydreaming",
                "Devil",
                "Dieting",
                "Different",
                "Drama",
                "Dream",
                "Drunk",
                "Engaged",
                "Fashion",
                "Fitness",
                "Fun",
                "Gem",
                "Gemini",
                "Ghosting",
                "Glowing",
                "Good",
                "Happy",
                "Hello",
                "Hi",
                "Home",
                "Hot",
                "Humble",
                "Ideal",
                "Immature",
                "Innocent",
                "Killer",
                "King",
                "Leo",
                "Libra",
                "Makeup",
                "Me",
                "OOPS",
                "Open-minded",
                "Organized",
                "Perfect",
                "Pisces",
                "Proud",
                "Queen",
                "Sagittarius",
                "Stunning",
                "Shh",
                "Sassy",
                "Savage",
                "Scorpio",
                "Single",
                "Smile",
                "Selfie",
                "Survivor",
                "Taurus",
                "TGIF",
                "Thriving",
                "Truth",
                "Unique",
                "Vibes",
                "Virgo",
                "Wide-eyed",
                "Wild",
                "Witty",
                "Wondering",
                "Worried",
                "Workout",
                "Absolutely",
                "Awards",
                "Awarded",
                "Awesome",
                "Awesomeness",
                "Blessed",
                "Celebrate",
                "Celebration",
                "Cheers",
                "Effort",
                "Excellent",
                "Extraordinary",
                "Genius",
                "Goals",
                "Grateful",
                "Great",
                "Hustling",
                "Impressive",
                "Magic",
                "OMG",
                "Rewards",
                "Rewarding",
                "Speechless",
                "Splendid",
                "Star",
                "Success",
                "Terrific",
                "Toast",
                "TOP!",
                "Top-notch",
                "Un.be.livable",
                "Wonderful",
                "Winning",
                "Winner",
                "Wonderful",
                "Yay",
                "Alive",
                "Aloha",
                "B.E.A.C.H.",
                "Beauty",
                "Bucketlist",
                "Blessed",
                "BRB",
                "Break",
                "Breathtaking",
                "Bye",
                "Ciao",
                "Cooling",
                "Daytrip",
                "Desert",
                "Destination",
                "Escape",
                "Enjoy",
                "Exquisite",
                "Extraordinary",
                "Forest",
                "Go",
                "Happiness",
                "Heaven",
                "Horizon",
                "Jungle",
                "Lovely",
                "Mood",
                "Nature",
                "Night",
                "Nocturnal",
                "Ocean",
                "Paradise",
                "Peace",
                "Rainbow",
                "Relax",
                "Roadtrip",
                "Sunshine",
                "Sunset",
                "Sunrise",
                "Shellebrate",
                "Sea",
                "Sky",
                "Travel",
                "Trip",
                "Unforgettable",
                "Unwind",
                "Vacation",
                "Wanderlust",
                "World",
                "YOLO",
                "MOOD",
                "#Facts",
                "Inspo",
                "Vibes",
                "Fri-YAY",
                "Cozy",
                "*Eyeroll*",
                "BOOM.",
                "Adventures",
                "Daydreaming",
                "Goals",
                "Feastmode",
                "TBT",
                "OOO",
                "Exploring"
    };


        public  static String[] attitude = new String[]{
                "If there is no one to hold your hand put your hands in your pocket and continue your walk.",
                "Don’t Judge Yourself With Others Because You Are Different From Them.",
                "If you ever think I am ignoring you, I swear I am. My phone is in my hand 24×7",
                "Your attitude is like a price tag, it shows how valuable you are.",
                "Don’t be afraid of being outnumbered, eagles fly alone. Pigeons flock together.",
                "People understand you by your attitude. If your attitude is bad you are bad. If your attitude is good you are good…",
                "My status is already high….",
                "Roses are red skies are blue, out of my five fingers the middle one is for you.",
                "My life, my rule, that’s my attitude…",
                "Do you think I’m bad? Then you’re wrong. I am the worst.",
                "My choices are like fingerprints, they make me unique.",
                "Dear girls, keep your heels and standards always high…!!",
                "Sometimes I want to treat people how they treat me But I don’t because It’s out of my character.",
                "I am me and that’s all I can be…I’m not perfect and never wanted to be…but I am happy with who I am even with what people think of me and I’m great to be me",
                "Finally gotten completely back to myself again :)) hearts closed, minds on :))",
                "In the beginning, you’ll judge me, by the end, you’ll love me.",
                "If you don’t want me, don’t fuck with my feelings.",
                "Me + my room + music + internet connection + no study = A PERFECT DAY……",
                "You left without a reason, so please don't come back with an excuse.",
                "I am not your toy.",
                "EMOTIONS, so never advertise your FEELINGS, just display your ATTITUDE",
                "Never Love Someone at The Cost of Your Dignity and Self Respect…!!!",
                "I don’t treat people badly; I treat them accordingly.",
                "Sometimes patience has limits….",
                "Sometimes I need expert advice… So, I talk to myself.",
                "If someone tells you that you are ugly. well, just be nice and say. Excuse me. I'M NOT YOUR MIRROR.",
                "If you don’t like something, change it. If you can’t change it, change your attitude.",
                "If attitude kills…. I am the weapon of mass destruction….",
                "If your ego speaks with me then my attitude replies to you.",
                "I am who I am and I won't change for anyone.",
                "SINGLE is not a status. It is a word that best describes a person who is strong enough to live and enjoy life without depending on other",
                "Life is like Facebook. People will like your problems and comment, but no one will solve them because everyone else is too busy updating theirs. There is no market for your",
                "Just finished blocking some numbers on WhatsApp, if you can read this then you got lucky…!!!",
                "You treated me like an option, so I left you like a choice",
                "I love the ones who are in my life and make it amazing. I also love the ones who left my life and made it fantastic.",
                "I’ve had enough of trying to prove myself to people. Now I don’t care about what people think as long as I’m happy with myself!",
                "Don’t stress, do your best, forget the rest.",
                "It’s very easy to defeat someone, but it’s very hard to win someone.",
                "I'm a very private person. You don’t ask I don’t tell.",
                "Your attitude may hurt me, but mine can Kill You!!",
                "I’m born to express, not to impress.",
                "Take care of Your Status, don’t be caretaker of My Status",
                "There are two ways to be happy: Change your situation, or change your mindset towards it.",
                "I don’t care for people, who don’t care for me.",
                "The Man with Beard will never Look Weird",
                "I don’t have an attitude problem. You have a problem with my attitude and that is not my problem.",
                "Before you judge me, Make sure that you’re perfect.",
                "Beauty is only skin deep. Attitude is down to the bone.",
                "Always remember, you are bigger than your problems…….",
                "Beauty captures your attention, but personality captures your heart.",
                "OH, I am sorry it’s my fault that I forgot you are a true idiot.",
                "I am a hot dude with a cool attitude.",
                "It is wise to adopt a change in life.",
                "Time is precious, waste it wisely.",
                "When I was born. The devil said:” Oh Shit…!! Competition”.",
                "Boys are great, every girl should have one.",
                "The one who is reading my status…Back off 🤚!!",
                "80% of the boy have girlfriends. The rest 20% are having a brain.",
                "Attitude and knowledge are the best foundation of real beauty.",
                "Don’t hate me, just get to know me first!",
                "Mistakes are proof that you’re trying.",
                "I am a winner which makes me a true competitor.",
                "We come from God but attitude is from the devil 👿.",
                "Follow your heart but don’t be stupid.",
                "I’m Not Special, I’m Just Limited Edition.",
                "I am not bad; I am worst in the kind 🦄.",
                "Losers always complain while champions train 💪",
                "My attitude based on how you treat me.",
                "Never bend your head. Always hold it high. Look the world straight in the eye.",
                "I love my job only when I’m on vacation.",
                "Always trying to cool my self",
                "Boys never realize how much one little thing can hurt a girl.",
                "A naughty thought a day keeps the stress away.",
                "I’m not lazy, I’m just on my energy saving mode.",
                "Guys have no idea how long something they said can stay in a girl’s mind.",
                "Never complain or adopt the habit to whine over small things and never ever justify yourself.",
                "Don’t try to mess with me because you will see different aspects of my great personality.",
                "I forgive but I never forget.",
                "Forget the haters…cause somebody loves you",
                "It’s simple. Love me for who I am not what you want me to be.",
                "I never make the same mistake twice. I make it five or six times, just to be sure.",
                "I never insult people I tell them what they actually are 👉.",
                "Little goals will make you expect little achievements so think big to win big success.",
                "The best thing about being me, I’m a limited edition and there are no other copies!",
                "Boys who don’t have a girlfriend surely have a brain.",
                "My Life My Rules.",
                "Smartness is a perfect beauty.",
                "Never argue with a fool or an idiot otherwise you will be known one of them.",
                "Always set the goals high 🎯 and don’t drop until you get the desired result 😎.",
                "My attitude is based on your behavior 😎.",
                "It’s my life, so keep your nose out of it.",
                "I need someone who sees the fire in my eyes and wants to play with it.",
                "Follow the rule of the sun 🌞. Shine and let the world burn 😎.",
                "Display your character with class and pride.",
                "Men hang out in bars for one of two reasons: Either they have no wife to go home to, or they do.",
                "Boys lie more, but girls lie better.",
                "I like to stay focused, chase my dreams, and move towards my aim and destiny 💪.",
                "Fashion is about something that comes from within you.",
                "I don’t have an attitude! Just a personality that you can’t handle!",
                "If you want me to control my temper, so control your stupidity.",
                "What I stand for is what I stand on 😎",
                "Only a champion is afraid of losing.",
                "Boys like me belonged to rain. 😎",
                "My determination is higher than my smartness.",
                "Do not call me nerdy or geeky because of glasses. It’s just I have beautiful eyes.",
                "My Girlfriend says I need to be more affectionate…Now I have 2 Girlfriends!",
                "Champions always try and play until they get it right 🏆",
                "It’s not my attitude, It’s my style.",
                "People with status don’t need status.",
                "ATTITUDE is everything.",
                "I am the architect of my own fate 🎯 and captain of my soul.",
                "Be silent and let your success shout.",
                "A break up in a relationship is like a mirror that is broken. It’s better to leave it the way it is than hurt yourself for fixing it.",
                "Do not meet your enemy with an angry face. Instead, rise and greet them with your smiling face. Nothing is more insulting than seeing your enemy happy and without a care.",
                "Some people live in the business of minding the business of other people.",
                "Being alone is better than being in a relationship with somebody who can fill the heart with doubt.",
                "When I loved you, I loved you very much that I never imagined hating you. But now that I abhor you, I hate you very much that I can never imagine loving you again.",
                "The secret to my happiness is expecting nothing from no one.",
                "A relationship is just made for two, but a few forget how to count.",
                "The words coming out of my mouth are all of me – unfiltered, raw, and real. Love it or hate it, it’s up to you.",
                "Everyone is unique in their own little ways.",
                "All this time, our relationship and my life focused on YOU and JUST YOU. I’ve had enough, and it is the right time that I start concentrating on ME and JUST ME.",
                "Albeit we’re breaking up, I’ll never hate the love that we formerly had. After all, it is not the fault of love that you never embraced the best and always marked the bad.",
                "Often, people who think highly of themselves are the ones who fall below than they can imagine.",
                "The way I deal with you is the reflection of the way you deal with me.",
                "If you intend to fool and play with my heart, you are making a big mistake. Pain has cast iron around the fences of my heart.",
                "It is better to be single than being with somebody who makes you feel alone.",
                "My attitude with love is simple – I do what I love and love will find me along the way.",
                "The pain that love has dealt with my heart forced me to grow up.",
                "I’m sorry that I can’t be the kind of person you can disrespect, manipulate, and twist around your fingers. I prefer that we finish things here and now and go our own separate ways.",
                "Everyone says winner never quits and not to renounce… But when I gave up on you, I won masses…",
                "Along the way, I will stumble a hundred times but I will get back up to my feet a hundred and more.",
                "Don’t anticipate me to tell you why I’m breaking up with you. Just like how you never informed me why you never got around for accepting me as a person I am.",
                "If you want to improve your life, start working on your attitude first.",
                "I’d rather be single and happy than be in a relationship and miserable.",
                "Your attitude screams about the bursting colors of your soul and the rhythm of your heart without the need for any words.",
                "You won’t find anyone like me. That’s why I call myself ‘limited edition’.",
                "I may not be perfect but I am one of a kind.",
                "At times, breakups are like bitter pills that heal you from toxic relationships.",
                "Let people think what they want to think about you. It’s none of your business anyway.",
                "Those whose head is above the clouds, with egos as high as towers are the ones who fall hard in the lowest depths of greed and shame.",
                "A few individuals do not realize what they tossed away until it is too late, and they cannot retrieve it.",
                "True love comes in all sizes and shapes except one – YOU.",
                "In love, if you fall easily on your knees, you will never win your happy ending.",
                "Relationships are extremely simple. They’re just two things that can come about. You either get married or break up.",
                "Attitude is the mirror of your entire being.",
                "Relationships are like fantastic road trips. Sit back and enjoy the stunning views in place of complaining about the potholes and the bumps.",
                "Do you acquaint why a preceding relationship is called ex? It is not the terminology for the past. It is a short form of Expired.",
                "I don’t have time to dwell in pain because I am too busy enjoying the things that make me happy."
        };
public static  String[] girl = new String[]
        {
                "Happy people are always beautiful.",
                "Take time to make your soul happy.",
                "Keep the smile on!",
                "If it makes you happy, do it a thousand and one times.",
                "Remember that there is never a shortage of beautiful reasons to be happy.",
                "Have the courage to be happy.",
                "Oh happy day.",
                "You decide your own happiness, so be happy as you want to.",
                "Studies suggest that the happier someone is, the more attractive they become.",
                "Smiles attract happiness like a magnet.",
                "Enjoying life as it is.",
                "Happy girls are the prettiest.",
                "You’re Never Completely Dressed Without A Smile.",
                "A smile never goes out of style.",
                "Be your own reason for your happiness.",
                "Look beyond all the imperfections and you’ll get a glimpse of happiness.",
                "Happy thoughts, happy life.",
                "It’s magical how happy you become once you make someone else happy.",
                "For every minute of unhappiness, you lose sixty seconds of happiness.",
                "If someone makes you happy, make them happier.",
                "Happy Girls Shine More.",
                "A Smile Is An Adorable Thing You Can Wear On.",
                "Happiness makes you glow better.",
                "Think of happiness as your default state, and you’ll be happier than ever.",
                "Happy is the new rich.",
                "A Smile Is The Most Beautiful Curve On A Woman’s Body.",
                "People often don’t realize that happiness doesn’t live in any one address. Happiness is actually everywhere!",
                "Beauty never asks for Attention.",
                "Braless is flawless.",
                "50% savage, 50% hotness",
                "Black as the devil, hot as hell, pure as an angel & sweet as love.",
                "Take off that shyness and wear some red.",
                "Wake up, workout, look hot.",
                "I am 99% angel, but oh, that 1%…",
                "Be your own kind of beautiful.",
                "Nothing is sexier than a girl who knows how to take control.",
                "Darling, I’m a nightmare, dressed like a daydream.",
                "Yes, I’m sexy and I know it.",
                "Be the badass with sexy ass.",
                "Take a ride on my energy.",
                "I’m not trying to be sexy, it’s just way of expressing myself when I move around.",
                "The best way to start my day is with our lips pressed together.",
                "Sexy doesn’t have to come with a price tag of being dumb.",
                "My lips are the gun. Smile is the trigger. My kisses are the bullets. Label me a killer.",
                "My Self Worth Is Not Determined By Others.",
                "Confidence Is True Beauty.",
                "I Am The Mixture Of A Cutie With A Mission And Hottie With An Ambition.",
                "No matter what a woman looks like, if she’s confident, she’s sexy.",
                "Be who you want to be and not what others want to see.",
                "I am the princess of my own Fairy Tale.",
                "I Am Sugar And Spice And Everything Nice, But If You Wanna Mess With Me, You Better Think Twice.",
                "Don’t Be Queen Waiting For A King. Be A Queen Busy With Her Kingdom Until Her King Arrives.",
                "There is a wolf in every girl.",
                "I did not dress this body up to come and waste it here.",
                "Brains make a woman classy.",
                "The few times I rule the world, they have to make everyone know.",
                "Imperfection is beauty, madness is genius, and it’s better to be absolutely ridiculous than absolutely boring.",
                "Strong women don’t have attitudes. They have standards.",
                "There is always a wild side to an innocent face.",
                "My attitude is inversely proportional to my height.",
                "I give my heart to whomever I want, that is why it is mine.",
                "I am the coolest devil at home.",
                "I come as a package, no room for trials.",
                "If it requires smiling, I probably won’t come.",
                "I feel like my attitude has an attitude of itself.",
                "Yeah, I’m single. And you’ll have to be amazing to change that.",
                "There’s always a wild side to an innocent face.",
                "No girl is me. She may be cute, but she is not me.",
                "People say I act like I don’t care. I’m not acting.",
                "I always laugh when people try to hurt my feelings. As if I have any.",
                "A smiling girl is the CEO of her own world.",
                "The world has a red carpet for any girl who is determined.",
                "Self-love is the greatest middle finger of all time.",
                "Like flowers, every girl has her season to blossom.",
                "There is a reason to live for the moment because tomorrow is just a promise.",
                "When life throws a rock at you, throw back a brick.",
                "A like in the morning will turn you into a legend by evening.",
                "Fake is a new trend and everyone seems to be in style.",
                "Be your own kind of beautiful.",
                "You are not gonna tell me who I m.",
                "Boys are like purses, cute, full of crap, and can always be replaced.",
                "You are magic, Don’t ever apologize for the fire in you.",
                "I am cool but global warming made me hot.",
                "Don’t show me your attitude as you can’t handle me.",
                "Do you hate me? I don’t care.",
                "There is a star high up for every girl, waiting for you to lift up your head.",
                "A woman has as many lives as her shoes.",
                "You are only down in order to build a foundation.",
                "Face the world with a smile, it will give up and smile back.",
                "I am who I am, Your approval is not needed.",
                "Beautiful girls rise with the sun every morning, to create new and beautiful memories.",
                "Don’t be like the rest of them.",
                "Women do not marry because they do not need anyone to advise them.",
                "I only need a smile to turn around a bad day.",
                "I may not be the best, but I know that I’m not like rest.",
                "I dress to impress myself.",
                "Punch as hard as you wish, I got a pile of makeup to seal any crack.",
                "People say I act like I don’t care. It’s not an act.",
                "I am unique.",
                "A woman is like a teabag, you will never know her strength until you put her in hot water.",
                "Heels will allow you to see far.",
                "Love me or hate me I’m still gonna shine.",
                "Don’t be ashamed of how someone else sees you. Be proud of who you are and what you are",
                "I literally have to remind myself all the time that being afraid of things going wrong isn't the way to make things go right.",
                "Dope days, chill nights, good company, and mellow vibes.",
                "Lighten up, just enjoy life. Smile more, laugh more, and don’t get so worked up about things.",
                "Do you know what true happiness is? Getting both your hair and makeup perfect at the same time",
                "Chin up, heads high – and you’re ready to conquer the world",
                "Happiness is having a bunch of freaking awesome and crazy friends.",
                "Why don’t scientists trust atoms? Because they make up everything.",
                "Be brave, be kind, be you.",
                "Walking with a friend in the dark is better than walking alone in the light.",
                "Real girls are never perfect and perfect girls are not real.",
                "Don’t walk behind me; I may not lead. Don’t walk in front of me; I may not follow. Just walk beside me and be my friend.",
                "My boyfriend says my mood swings are hard to understand. Well, hello! They’re not as hard as quantum physics",
                "Who’s that beauty queen? Oops! I clicked on my profile picture again",
                "According to research, chubby women live longer than men who mention it",
                "Why am I late? My nail polishes had to dry first",
                "NASA just announced that it is safe to eat without posting it on Instagram.",
                "I like to hang out with people who make me forget to look at my phone.",
                "Always remember you’re unique, just like everyone else.",
                "You only live once, but if you do it right, once is enough.",
                "You have to be ODD, to be number ONE.",
                "Your crowd should be clapping loudest when you win. If they don’t, look for a new crowd.",
                "You can’t pour from an empty cup. Take care of yourself first.",
                "Oh, I’m sorry. I forgot I only exist when you need something.",
                "There’s a fire in every woman. Love her and she’ll make your home warm. Hurt her, and she’ll burn it to ashes",
                "I need a vacation so long, I forget all my passwords!",
                "May your day be as good as taking a perfect selfie on the first try.",
                "Tell me not to do something and I will do it twice and take pictures.",
                "Behind every successful women is herself.",
                "Be proud of who you are, and not ashamed of how someone else sees you.",
                "I’m not beautiful like you. I’m beautiful like me.",
                "I’m no beauty queen, I’m just beautiful me.",
                "The world has a red carpet for any girl who is determined.",
                "Self-love is the greatest middle finger of all time.",
                "If you are confident, You are beautiful.",
                "Confidence is the ability to feel Beautiful, without needing someone to tell you.",
                "Beauty begins the moment you decided to be yourself.",
                "The most beautiful thing a woman can wear is confidence.",
                "Don’t forget to fall in love with yourself first.",
                "A wise girl knows her limits, a smart girl knows that she has none.",
                "You may see me struggle, but you’ll never see me quit.",
                "Be yourself there is no one better.",
                "Quit trying to fix me, I am not broken.",
                "Some call it arrogant, I call it confident.",
                "What others think of me is none of my business.",
                "Love me or hate me either way I’m gonna shine.",
                "I think beautiful is like you take care of yourself.",
                "Nothing makes a woman more beautiful than the belief that she is beautiful.",
                "Remind yourself that you cannot fail at being yourself.",
                "Be your own reason to smile.",
                "When I feel a little down, I put on my favorite high heels and dance.",
                "Know your worth.",
                "I’m not short, I’m concentrated awesome!",
                "Never a failure, always a lesson.",
                "My self worth is not determined by others.",
                "Love your haters, they’re your biggest fans.",
                "Be yourself because an original is worth more than a copy.",
                "A girl should be like a butterfly. Pretty to see, hard to catch.",
                "Sometimes you gotta be a beauty and a beast!",
                "Love me or hate me either way I’m gonna shine.",
                "I’m not short, I’m concentrated awesome!",
                "Money can’t buy happiness. But it can buy Makeup!",
                "Sometimes I pretend to be normal. But it gets boring. So I go back to being.",
                "Be so good they can’t ignore you.",
                "Born to express, not to impress.",
                "Embrace the glorious mess that you are.",
                "Lift up your head princess, if not the crown falls.",
                "Weekend, please don’t leave me.",
                "Be your own kind of beautiful.",
                "I love it when I catch you looking at me.",
                "My favorite place is inside your hug.",
                "My boyfriend still thinks my eyelashes are real. I guess we all have secrets, Don’t we?",
                "My hobbies are breakfast, lunch, and dinner.",
                "Cinderella never asked for a prince.",
                "Talking to you makes my day.",
                "The way you make me feel I love that feeling.",
                "I need vitamin u.",
                "Sunday FUNDAY.",
                "Sometimes it’s the princess who kills the dragon and saves the prince.",
                "All I need is Coffee and Mascara.",
                "Smile, it’s free therapy.",
                "I love the confidence that makeup gives me.",
                "Create your own magic.",
                "Behind every successful woman is herself.",
                "Be Who You Want To Be And Not What Others Want To See.",
                "No matter how you’re feeling: Go get up, Dress up, Show up and Never you dare to give up.",
                "Life Is Not Perfect, But My Hair Is!",
                "Keep Your Heels And Standards High.",
                "Dress To Impress.",
                "I have fallen in love with the confidence that makeup brings in me.",
                "Be a diamond esteemed and rare, not a stone found everywhere.",
                "Happiness Is..new Cosmetics, Many Of Them.",
                "Don’t Forget To Fall In Love With Yourself First.",
                "Don’t Believe Me When I Say I Will Be Ready In 2 Minutes.",
                "Beauty Begins The Moment You Decided To Be Yourself.",
                "Surround yourself with makeup, not negativity.",
                "I’m No Beauty Queen, I’m Just Beautiful Me.",
                "Real beauty never asks for attention.",
                "So Many Nail Polishes, Not Enough Fingers.",
                "I Know Looks Are Not Everything But I Have Them Just In Case.",
                "Elegance is the only beauty that never fades.",
                "It’s Better To Arrive Late Than To Arrive Ugly.",
                "Curls Run The World.",
                "Cute Girls Can Never Be Overdressed.",
                "Being stylish is about enjoying your life and expressing yourself and your inner light.",
                "Makeup Is Art. Beauty Is Passion.",
                "Life is too short to wear any boring clothes.",
                "The beauty of a woman must be seen from in her eyes because that is the doorway to her heart, the place where love resides.",
                "I Run On Coffee, Sarcasm, And Lipstick.",
                "With A Good Makeup Brush, Every Woman Can Be An Artist.",
                "Confidence Level: Selfie with no Filter.",
                "This is the most magical pic of your life.",
                "Dream without fear, love without limits.",
                "Sending my selfie to NASA, because I’m a star.",
                "Warning – You might fall in love with me.",
                "I am not trying to be cool, It’s what I am.",
                "Sparkle every single day.",
                "Wakeup and makeup",
                "Be happy; it drives people crazy.",
                "I did NOT wake up like this.",
                "The sky above me, earth below me & fire within me.",
                "Live for the moments you can’t put into words.",
                "I love looking in the mirror and feeling good about what I see.",
                "I was born to stand out.",
                "Classy & Fabulous",
                "A selfie a day keeps the doctor away!",
                "Smile, breathe and go slowly.",
                "You only live once, but if you do it right, once is enough.",
                "Crazy hair, don’t care.",
                "You cannot do EPIC shit with basic people.",
                "Be yourself, there’s no one better.",
                "Being part of this group is so much fun, I love it.",
                "Life is better when you’re laughing.",
                "If I send you ugly selfies, our friendship is real.",
                "I just got 30 likes, #selfiepro",
                "Normal is boring for me.",
                "Surround yourself with those who make you happy.",
                "Moments like these…This is what we live for, this is why we exist.",
                "I’m in desperate need of a 6-month vacation…twice a year.",
                "I’m on a seafood diet. When I see food, I eat it. Happy girls are the prettiest.",
                "Every woman is an angel, you only need to take her to heaven.",
                "I am dating anyone who hearts my status, that is what the hearts are meant for.",
                "I’m not short, I’m concentrated awesome!",
                "Catch flights, not feelings.",
                "The most beautiful woman is one who puts on a smile as her makeup every morning.",
                "God looked at the boring hairstyle of Adam and said, “Let’s create someone with a more creative head”.",
                "If you got eyes, look at me now.",
                "My bed is a magical place, I suddenly remember everything I forgot to do.",
                "When life gives you lemons, use them to make your skin glow.",
                "Believe in pink.",
                "There is nothing so serious about life, we are here to eat, look beautiful then die.",
                "I am not fat. I’m just much easier to see.",
                "The main reason Santa is so jolly is because he knows where all the bad girls live.",
                "Happiness is a new lipstick.",
                "Women have many faces, depending on who is looking.",
                "Behind every successful woman are her dreams to rule the world.",
                "Leave a little sparkle wherever you go.",
                "Inner beauty needs no makeup.",
                "Be You Till Full.",
                "If your dreams appear impossible, there is a wrong man in your life.",
                "No matter how you feel, get up, dress up, show up and never give up.",
                "So many nail polishes, not enough fingers.",
                "Have courage and be kind.",
                "Life is short to those with no makeup.",
                "All I need is coffee & mascara.",
                "The most beautiful hair is a brilliant mind.",
                "Women are never fat, it is their love that grows from within.",
                "Good girls go to heaven when they die only to find that all handsome angels are taken by beautiful girls.",
                "Speak english. Kiss french. Dress italian. Spend arab. Party caribbean.",
                "God is really creative, I mean just look at me.",
                "Curls run the world.",
                "Smile. Sparkle. Shine.",
                "I’m that quiet girl who is absolutely insane with her friends.",
                "Cute but psycho, yet cute.",
                "The most beautiful curve on a woman’s body is her smile.",
                "The purity of heart and sincerity in a smile.",
                "I don’t know whether love brings happiness or sadness, but it definitely brings something called ‘CHANGE.’",
                "Smile in the mirror. Do that every morning and you’ll start to see a big difference in your life.",
                "The most beautiful woman is one who puts on a smile as her makeup every morning.",
                "If you don’t have a smile, I’ll give you one of mine.!",
                "Never love anyone who treats you like you’re ordinary.",
                "A smile is an inexpensive way to change your looks.",
                "I’m a sweet girl. But honey, make me mad, and only God can save you",
                "I’m an odd combination of REALLY SWEET and DON’T MESS WITH ME!!!",
                "Keep smiling because life’s a beautiful thing and there’s so much to smile about.",
                "They say that good things take time, but really great things happen in the blink of an eye.",
                "Sometimes I pretend to be normal. But it gets boring. So I go back to being.",
                "Some girls are just born with glitter in their veins.",
                "If there were an award for being lazy, I would definitely send someone to get it for me",
                "I try to be a nice person, but sometimes my mouth doesn’t want to cooperate!",
                "A smile is the most beautiful curve on a woman’s body.",
                "I love it when I catch you looking at me.",
                "Twinkle, Twinkle little star, Brave & Beautiful is what you are.",
                "If people call me cute, I am happier.",
                "When you’re downie eat a brownie.",
                "It's better to be happy alone than unhappy with someone.",
                "I restore myself when I’m alone.",
                "I need some time alone with myself.",
                "When we truly realize that we are all alone is when we need others the most.",
                "Don't feel alone, because there is always someone out there who loves you more than you can imagine.",
                "The best part about being alone is that you really don't have to answer to anybody. You do what you want. ",
                "Learn to be alone, not everyone will stay forever.",
                "Maybe I should learn not to get toon attached.",
                "It’s hard to forget someone that gave you so much to remember.",
                "Sometimes its better to be alone, no one can hurt you that way.  ",
                "You cannot be lonely if you like the person you're alone with.",
                "Never lose your hope even if you are alone.",
                "Emptiness feels so heavy.",
                "I’m simple to understand. Like quantum physics.",
                "I used to think that the worst thing in life was to end up all alone. It's not. The worst thing in life is ending up with people who make you feel all alone.",
                "If you are afraid of being lonely, don't try to be right.",
                "I miss your smile but I miss my own more.",
                "Time changes everyone.",
                "Sometimes you have to stand alone just to make sure you still can.",
                "Boys are like purses, cute, full of crap, and can always be replaced.",
                "I love to be alone.",
                "Loneliness adds beauty to life. It puts a special burn on sunsets and makes night air smell better.",
                "As I get older I'm more and more comfortable being alone.    ",
                "Never be afraid to sit awhile and think.  "
        };
    public static String[] Answer = new String[]{
            "Answer 48",
            "Answer 3",
            "Answer 100",
    };
}
